/**
 * Gen 1/2 Pokemon typing table — used only by the RBY/GSC stat-screen
 * renderer to display TYPE1/TYPE2 fields. Indexed by national dex
 * (1..251). Source: pret/pokered + pret/pokecrystal `data/pokemon/base_stats/*.asm`
 * type bytes (Gen 1/2 era, before Fairy/Steel-on-Magnemite-Gen-1 retcons).
 *
 * Magnemite/Magneton are ELECTRIC/STEEL here (Gen 2 retcon — Gen 2 added
 * Steel/Dark and back-applied Steel to the Magnemite line). Gen 1 carts
 * still report them as ELECTRIC-only at runtime; the visual stat-screen
 * accepts either since this table is purely cosmetic.
 *
 * Pre-Gen-6 typing — Clefairy / Clefable / Jigglypuff / Wigglytuff /
 * Snubbull / Granbull etc. are NORMAL here, not Fairy.
 */

export type TypeName =
  | 'NORMAL' | 'FIRE' | 'WATER' | 'ELECTRIC' | 'GRASS' | 'ICE'
  | 'FIGHTING' | 'POISON' | 'GROUND' | 'FLYING' | 'PSYCHIC'
  | 'BUG' | 'ROCK' | 'GHOST' | 'DRAGON' | 'DARK' | 'STEEL';

const TABLE: Readonly<Record<number, readonly [TypeName, TypeName | null]>> = {
  1: ['GRASS', 'POISON'],   2: ['GRASS', 'POISON'],   3: ['GRASS', 'POISON'],
  4: ['FIRE', null],        5: ['FIRE', null],        6: ['FIRE', 'FLYING'],
  7: ['WATER', null],       8: ['WATER', null],       9: ['WATER', null],
  10: ['BUG', null],       11: ['BUG', null],        12: ['BUG', 'FLYING'],
  13: ['BUG', 'POISON'],   14: ['BUG', 'POISON'],    15: ['BUG', 'POISON'],
  16: ['NORMAL', 'FLYING'], 17: ['NORMAL', 'FLYING'], 18: ['NORMAL', 'FLYING'],
  19: ['NORMAL', null],    20: ['NORMAL', null],
  21: ['NORMAL', 'FLYING'], 22: ['NORMAL', 'FLYING'],
  23: ['POISON', null],    24: ['POISON', null],
  25: ['ELECTRIC', null],  26: ['ELECTRIC', null],
  27: ['GROUND', null],    28: ['GROUND', null],
  29: ['POISON', null],    30: ['POISON', null],
  31: ['POISON', 'GROUND'],
  32: ['POISON', null],    33: ['POISON', null],
  34: ['POISON', 'GROUND'],
  35: ['NORMAL', null],    36: ['NORMAL', null],
  37: ['FIRE', null],      38: ['FIRE', null],
  39: ['NORMAL', null],    40: ['NORMAL', null],
  41: ['POISON', 'FLYING'], 42: ['POISON', 'FLYING'],
  43: ['GRASS', 'POISON'], 44: ['GRASS', 'POISON'], 45: ['GRASS', 'POISON'],
  46: ['BUG', 'GRASS'],    47: ['BUG', 'GRASS'],
  48: ['BUG', 'POISON'],   49: ['BUG', 'POISON'],
  50: ['GROUND', null],    51: ['GROUND', null],
  52: ['NORMAL', null],    53: ['NORMAL', null],
  54: ['WATER', null],     55: ['WATER', null],
  56: ['FIGHTING', null],  57: ['FIGHTING', null],
  58: ['FIRE', null],      59: ['FIRE', null],
  60: ['WATER', null],     61: ['WATER', null],
  62: ['WATER', 'FIGHTING'],
  63: ['PSYCHIC', null],   64: ['PSYCHIC', null],   65: ['PSYCHIC', null],
  66: ['FIGHTING', null],  67: ['FIGHTING', null],  68: ['FIGHTING', null],
  69: ['GRASS', 'POISON'], 70: ['GRASS', 'POISON'], 71: ['GRASS', 'POISON'],
  72: ['WATER', 'POISON'], 73: ['WATER', 'POISON'],
  74: ['ROCK', 'GROUND'],  75: ['ROCK', 'GROUND'],  76: ['ROCK', 'GROUND'],
  77: ['FIRE', null],      78: ['FIRE', null],
  79: ['WATER', 'PSYCHIC'], 80: ['WATER', 'PSYCHIC'],
  81: ['ELECTRIC', 'STEEL'], 82: ['ELECTRIC', 'STEEL'],
  83: ['NORMAL', 'FLYING'],
  84: ['NORMAL', 'FLYING'], 85: ['NORMAL', 'FLYING'],
  86: ['WATER', null],     87: ['WATER', 'ICE'],
  88: ['POISON', null],    89: ['POISON', null],
  90: ['WATER', null],     91: ['WATER', 'ICE'],
  92: ['GHOST', 'POISON'], 93: ['GHOST', 'POISON'], 94: ['GHOST', 'POISON'],
  95: ['ROCK', 'GROUND'],
  96: ['PSYCHIC', null],   97: ['PSYCHIC', null],
  98: ['WATER', null],     99: ['WATER', null],
  100: ['ELECTRIC', null], 101: ['ELECTRIC', null],
  102: ['GRASS', 'PSYCHIC'], 103: ['GRASS', 'PSYCHIC'],
  104: ['GROUND', null],   105: ['GROUND', null],
  106: ['FIGHTING', null], 107: ['FIGHTING', null],
  108: ['NORMAL', null],
  109: ['POISON', null],   110: ['POISON', null],
  111: ['GROUND', 'ROCK'], 112: ['GROUND', 'ROCK'],
  113: ['NORMAL', null],
  114: ['GRASS', null],
  115: ['NORMAL', null],
  116: ['WATER', null],    117: ['WATER', null],
  118: ['WATER', null],    119: ['WATER', null],
  120: ['WATER', null],    121: ['WATER', 'PSYCHIC'],
  122: ['PSYCHIC', null],
  123: ['BUG', 'FLYING'],
  124: ['ICE', 'PSYCHIC'],
  125: ['ELECTRIC', null], 126: ['FIRE', null],
  127: ['BUG', null],
  128: ['NORMAL', null],
  129: ['WATER', null],    130: ['WATER', 'FLYING'],
  131: ['WATER', 'ICE'],
  132: ['NORMAL', null],
  133: ['NORMAL', null],
  134: ['WATER', null],    135: ['ELECTRIC', null], 136: ['FIRE', null],
  137: ['NORMAL', null],
  138: ['ROCK', 'WATER'],  139: ['ROCK', 'WATER'],
  140: ['ROCK', 'WATER'],  141: ['ROCK', 'WATER'],
  142: ['ROCK', 'FLYING'],
  143: ['NORMAL', null],
  144: ['ICE', 'FLYING'],  145: ['ELECTRIC', 'FLYING'], 146: ['FIRE', 'FLYING'],
  147: ['DRAGON', null],   148: ['DRAGON', null],   149: ['DRAGON', 'FLYING'],
  150: ['PSYCHIC', null],  151: ['PSYCHIC', null],
  152: ['GRASS', null],    153: ['GRASS', null],    154: ['GRASS', null],
  155: ['FIRE', null],     156: ['FIRE', null],     157: ['FIRE', null],
  158: ['WATER', null],    159: ['WATER', null],    160: ['WATER', null],
  161: ['NORMAL', null],   162: ['NORMAL', null],
  163: ['NORMAL', 'FLYING'], 164: ['NORMAL', 'FLYING'],
  165: ['BUG', 'FLYING'],  166: ['BUG', 'FLYING'],
  167: ['BUG', 'POISON'],  168: ['BUG', 'POISON'],
  169: ['POISON', 'FLYING'],
  170: ['WATER', 'ELECTRIC'], 171: ['WATER', 'ELECTRIC'],
  172: ['ELECTRIC', null],
  173: ['NORMAL', null],   174: ['NORMAL', null],
  175: ['NORMAL', null],   176: ['NORMAL', 'FLYING'],
  177: ['PSYCHIC', 'FLYING'], 178: ['PSYCHIC', 'FLYING'],
  179: ['ELECTRIC', null], 180: ['ELECTRIC', null], 181: ['ELECTRIC', null],
  182: ['GRASS', null],
  183: ['WATER', null],    184: ['WATER', null],
  185: ['ROCK', null],
  186: ['WATER', null],
  187: ['GRASS', 'FLYING'], 188: ['GRASS', 'FLYING'], 189: ['GRASS', 'FLYING'],
  190: ['NORMAL', null],
  191: ['GRASS', null],    192: ['GRASS', null],
  193: ['BUG', 'FLYING'],
  194: ['WATER', 'GROUND'], 195: ['WATER', 'GROUND'],
  196: ['PSYCHIC', null],  197: ['DARK', null],
  198: ['DARK', 'FLYING'],
  199: ['WATER', 'PSYCHIC'],
  200: ['GHOST', null],
  201: ['PSYCHIC', null],  202: ['PSYCHIC', null],
  203: ['NORMAL', 'PSYCHIC'],
  204: ['BUG', null],      205: ['BUG', 'STEEL'],
  206: ['NORMAL', null],
  207: ['GROUND', 'FLYING'],
  208: ['STEEL', 'GROUND'],
  209: ['NORMAL', null],   210: ['NORMAL', null],
  211: ['WATER', 'POISON'],
  212: ['BUG', 'STEEL'],
  213: ['BUG', 'ROCK'],
  214: ['BUG', 'FIGHTING'],
  215: ['DARK', 'ICE'],
  216: ['NORMAL', null],   217: ['NORMAL', null],
  218: ['FIRE', null],     219: ['FIRE', 'ROCK'],
  220: ['ICE', 'GROUND'],  221: ['ICE', 'GROUND'],
  222: ['WATER', 'ROCK'],
  223: ['WATER', null],    224: ['WATER', null],
  225: ['ICE', 'FLYING'],
  226: ['WATER', 'FLYING'],
  227: ['STEEL', 'FLYING'],
  228: ['DARK', 'FIRE'],   229: ['DARK', 'FIRE'],
  230: ['WATER', 'DRAGON'],
  231: ['GROUND', null],   232: ['GROUND', null],
  233: ['NORMAL', null],
  234: ['NORMAL', null],
  235: ['NORMAL', null],
  236: ['FIGHTING', null], 237: ['FIGHTING', null],
  238: ['ICE', 'PSYCHIC'],
  239: ['ELECTRIC', null], 240: ['FIRE', null],
  241: ['NORMAL', null],   242: ['NORMAL', null],
  243: ['ELECTRIC', null], 244: ['FIRE', null], 245: ['WATER', null],
  246: ['ROCK', 'GROUND'], 247: ['ROCK', 'GROUND'], 248: ['ROCK', 'DARK'],
  249: ['PSYCHIC', 'FLYING'],
  250: ['FIRE', 'FLYING'],
  251: ['PSYCHIC', 'GRASS'],
};

export function getTypesGen2(ndex: number): readonly [TypeName, TypeName | null] {
  return TABLE[ndex] ?? ['NORMAL', null];
}
