/**
 * "Oracle B" byte-equality test (PLAN_EVAL A4 / A8). Compares production
 * `packBoxed` output against committed hex vectors generated by
 * `scripts/gen-pkhex-vector.ts` — an independent reimplementation of
 * the Gen 3 wire format that does NOT import any production pack code.
 *
 * If this test fails, EITHER the production packer or the harness packer
 * has a bug; the diagnostic message indicates which fixture and at what
 * byte offset the divergence occurred.
 */

import { describe, expect, it } from 'vitest';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { convert, isRefusal, packBoxed } from '../../core/src/index.js';
import { pikachuUntrainedLv25 } from '../fixtures/pikachu-untrained-lv25.js';
import { feraligatrUntrainedLv55 } from '../fixtures/feraligatr-untrained-lv55.js';
import { snorlaxMaxTrained } from '../fixtures/snorlax-maxtrained.js';
import { alakazamCompetitive } from '../fixtures/alakazam-competitive.js';
import { partialTrained } from '../fixtures/partial-trained.js';
import type { Gen12Pokemon } from '../../core/src/types/source.js';

const SRC_BY_LABEL: Readonly<Record<string, Gen12Pokemon>> = {
  'pikachu-untrained-lv25': pikachuUntrainedLv25,
  'feraligatr-untrained-lv55': feraligatrUntrainedLv55,
  'snorlax-maxtrained': snorlaxMaxTrained,
  'alakazam-competitive': alakazamCompetitive,
  'partial-trained': partialTrained,
};

interface OracleVector {
  label: string;
  pid: string;
  tid: number;
  sid: number;
  species: number;
  boxedHex: string;
}

function hexToBytes(hex: string): Uint8Array {
  if (hex.length % 2 !== 0) throw new Error(`hex length ${hex.length} not even`);
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.substr(i * 2, 2), 16);
  return out;
}

const here = dirname(fileURLToPath(import.meta.url));
const fixturePath = resolve(here, '..', 'fixtures', 'pkhex', 'oracle-vectors.json');
const vectors: OracleVector[] = JSON.parse(await readFile(fixturePath, 'utf8'));

describe('Oracle B byte-equality (independent harness packer)', () => {
  for (const v of vectors) {
    it(`production packBoxed === oracle ${v.label}`, () => {
      const src = SRC_BY_LABEL[v.label];
      if (!src) throw new Error(`No source fixture for label "${v.label}"`);
      const it = convert(src);
      if (isRefusal(it)) throw new Error(`${v.label}: unexpected refusal`);
      const expected = hexToBytes(v.boxedHex);
      const actual = packBoxed(it);
      expect(actual.length).toBe(80);
      expect(expected.length).toBe(80);
      // Byte-by-byte assertion produces a clean diff at the first mismatch.
      for (let off = 0; off < 80; off++) {
        if (actual[off] !== expected[off]) {
          throw new Error(
            `${v.label}: diverge at offset ${off}: actual=0x${actual[off]!.toString(16)} expected=0x${expected[off]!.toString(16)}`,
          );
        }
      }
    });
  }
});
