/**
 * Gen 3 internal-storage-id → National Dex translation.
 *
 * Gen 3 saves store species using INTERNAL ids that diverge from
 * national dex starting at 252. Internals 252-276 are placeholder
 * OLD_UNOWN slots (collapsing to ndex 201 in pkhex/legality terms).
 * From internal 277 (Treecko) onwards, Game Freak coded Hoenn species
 * in non-dex order, so e.g. Bagon's internal id is 395 / national dex
 * 371. Reading a Bagon slot's species byte returns 395; this map gives
 * back 371 so the rest of the pipeline (sprite paths, name lookups)
 * can stay national-dex-keyed.
 *
 * Generated by `scripts/gen-species-names.py` from pret/pokeemerald
 * (`include/constants/species.h` + `include/constants/pokedex.h`).
 * Re-pull with `python3 scripts/gen-species-names.py`.
 */

import raw from '../../data/raw/gen3-internal-to-ndex.json' with { type: 'json' };

const TABLE: ReadonlyMap<number, number> = new Map(
  Object.entries(raw as Record<string, number>).map(([k, v]) => [Number(k), v]),
);

/** Translate a Gen 3 internal storage id → national dex. Internal ids
 *  that don't map to a real species (OLD_UNOWN_B..Z = 252-276, the
 *  uninhabited slots above 411) return 0 — caller should treat as
 *  "unknown / out-of-range". */
export function gen3InternalToNdex(internalId: number): number {
  return TABLE.get(internalId) ?? 0;
}
